---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replication-controllers
spec:
  minReadySeconds: 2
  replicas: 5
  selector:
    app: nginx
  template:
    metadata:
      name: nginx-replicas
      labels:
        app: nginx
        ver: "1.23"
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - containerPort: 80
              protocol: TCP
