---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc-lb
spec:
  type: LoadBalancer
  selector:
    app: nginx
    ver: "1.0"
  ports:
    - name: webport
      port: 35000
      targetPort: 80
